//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTSMS
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class PROD_CMSEntities : DbContext
    {
        public PROD_CMSEntities()
            : base("name=dev_CMSEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<TrainingApplication> TrainingApplications { get; set; }
    }
}
