//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingApplication
    {
        public string Salutation { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public string CellPhone { get; set; }
        public string HomePhone { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string EducationalLevel { get; set; }
        public string ApplyingForProgram { get; set; }
        public string CertificateType { get; set; }
        public string Category { get; set; }
    }
}
